#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>


void init_localizer(const char *to_localize_file_path);

const char *translation_file_name_for_address(uintptr_t address);
